In [2]:
# Imports needed for this notebook
import numpy as np

# What & Why of Linear Algebra

- Study of "vector spaces"; relationship of **linear** relationships
- Uses vectors, matrices, and tensors
- Mapping & dimensionality (PCA)
- Used in lots of ML applications


We'll try to put abstract ideas into the formalism of linear algebra
 - images/pixels
 - language (NLP)


# Different Tensors

## Scalars, Vectors, Matrices: It's all about the dimension

In [ ]:
# Scalar
s = np.arange(1)
display(s)

In [3]:
# Vector
v = np.arange(4)
display(v)

# Other ways to define vector
x = np.linspace(-np.pi, np.pi, 10)
display(x)

array([0, 1, 2, 3])

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [ ]:
# Matrix
M = np.arange(4 * 2).reshape((4, 2))
display(M)

In [ ]:
# 3D Tensor
T_3d = np.arange(4 * 2 * 3).reshape((4, 2, 3))
display(T_3d)

### Indexing with NumPy

In [4]:
# For Vectors
print (v[1:4])     # second to fourth element. Element 5 is not included
print (v[::2])  # every other element
print (v[:])       # print the whole vector
print (v[::-1])    # reverse the vector!

[1 2 3]
[0 2]
[0 1 2 3]
[3 2 1 0]


# Basic Properties

# Creating with NumPy